---
name: Build & Test
on:
  push:
    branches:
      - '**'
permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.1'
          cache: true
      - run: go build -v
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP2AWS_GCP_WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP2AWS_GCP_GITHUB_ACTIONS_SERVICE_ACCOUNT_EMAIL}}
      - uses: paambaati/codeclimate-action@v8
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          GCP2AWS_GCP_SERVICE_ACCOUNT_EMAIL: ${{secrets.GCP2AWS_GCP_SERVICE_ACCOUNT_EMAIL}}
          GCP2AWS_AWS_ROLE_ARN: ${{secrets.GCP2AWS_AWS_ROLE_ARN}}
        with:
          coverageCommand: go test -v -cover -coverprofile cover.out
          coverageLocations: ${{github.workspace}}/cover.out:gocov
          prefix: github.com/${{github.repository}}
